// ── Language Translation Framework ──

const FBLang = {
  translations: {
    en: {
      nav_features: "Features",
      nav_how_it_works: "How It Works",
      nav_impact: "Impact",
      nav_login: "Login",
      nav_signup: "Sign Up",
      nav_dashboard: "Dashboard",
      nav_donate: "Donate Food",
      nav_donations: "My Donations",
      nav_track: "Track Orders",
      nav_stats: "Impact Stats",
      hero_title: "Reduce Food Waste, Feed the Needy",
      hero_subtitle: "A seamless bridge between surplus food and NGOs",
      hero_btn_donate: "Donate Food",
      hero_btn_find: "Find Food",
      features_title: "Why Choose FoodBridge?",
      feature_1_title: "Location-based Matching",
      feature_2_title: "Safe Handling",
      feature_3_title: "Real-time Tracking",
      feature_4_title: "Impact Tracking",
      how_title: "Simple 3-Step Process",
      step_1_title: "Add Food Details",
      step_2_title: "Match with NGO",
      step_3_title: "Pickup & Delivery",
      stat_meals: "Meals Donated",
      stat_people: "People Helped",
      stat_donors: "Active Donors",
      stat_ngos: "Joined NGOs",
      footer_tagline: "Connecting communities to ensure extra food reaches those who need it most.",
      login_title: "Welcome Back",
      login_subtitle: "Join the movement to end food waste",
      login_role_donor: "Donor",
      login_role_ngo: "NGO",
      login_role_admin: "Admin",
      login_email: "Email Address",
      login_password: "Password",
      login_remember: "Remember me",
      login_forgot: "Forgot Password?",
      login_btn: "Login to Account",
      login_no_account: "Don't have an account?",
      login_signup: "Sign Up",
      login_back_home: "Back to Home",
      login_or: "Or continue with",
      signup_title: "Create Account",
      signup_subtitle: "Join FoodBridge today",
      signup_name: "Full Name",
      signup_email: "Email Address",
      signup_phone: "Phone Number",
      signup_password: "Password",
      signup_confirm: "Confirm Password",
      signup_btn: "Create Account",
      signup_have_account: "Already have an account?",
      signup_login: "Login",
      donor_welcome: "Welcome back",
      donor_subtitle: "Make a difference today",
      donor_new_donation: "New Donation",
      donor_total_donations: "Total Donations",
      donor_meals_provided: "Meals Provided",
      donor_people_helped: "People Helped",
      donor_active: "Active Donations",
      donor_history: "Donation History",
      donor_surplus_title: "Have surplus food?",
      donor_surplus_subtitle: "Post a donation in 2 minutes",
      donor_impact_title: "Your Impact This Month 🌟",
      donor_recent_title: "My Recent Donations",
      donor_track: "Track",
      donor_status_pending: "Pending",
      donor_status_accepted: "Accepted",
      donor_status_delivered: "Delivered",
      form_title: "Add New Donation",
      form_food_name: "Food Name",
      form_food_type: "Food Type",
      form_quantity: "Quantity",
      form_expiry: "Expiry Time",
      form_address: "Pickup Address",
      form_notes: "Additional Notes",
      form_submit: "Submit Donation",
      form_cancel: "Cancel",
      ngo_welcome: "Welcome",
      ngo_available: "Available Donations",
      ngo_accepted: "Accepted",
      ngo_schedule: "Schedule",
      ngo_accept_btn: "Accept",
      ngo_decline_btn: "Decline",
      ngo_available_subtitle: "donations available near you today.",
      ngo_sos_alerts: "Active SOS Alerts",
      ngo_sos_recent: "My Recent SOS",
      ngo_nav_overview: "Overview",
      ngo_nav_available: "Available",
      ngo_nav_accepted: "Accepted",
      ngo_nav_schedule: "Schedule",
      ngo_nav_volunteers: "Volunteers",
      ngo_nav_reports: "Reports",
      ngo_nav_profile: "Profile",
      ngo_stat_available: "Available Near Me",
      ngo_stat_accepted: "Accepted Today",
      ngo_stat_received: "Total Received",
      ngo_stat_volunteers: "Volunteers Active",
      admin_title: "Admin Panel",
      admin_users: "Total Users",
      admin_donations: "Total Donations",
      admin_ngos: "Active NGOs",
      admin_complaints: "Complaints",
      common_logout: "Logout",
      common_profile: "Profile",
      common_notifications: "Notifications",
      common_settings: "Settings",
      common_save: "Save Changes",
      common_cancel: "Cancel",
      common_delete: "Delete",
      common_search: "Search...",
      common_loading: "Loading...",
      common_no_data: "No data found",
      common_back: "Back",
      sos_title: "Food SOS 🆘",
      sos_subtitle: "Too much food? Need NGO urgently?",
      sos_btn: "Send SOS Alert",
      sos_sending: "Sending alert...",
      sos_sent: "SOS Alert Sent! ✅",
      sos_active: "Active SOS Alert",
      sos_cancel: "Cancel SOS",
      sos_history: "Previous SOS Alerts",
      notif_title: "Notifications",
      notif_mark_all: "Mark all as read",
      notif_empty: "No notifications yet",
      profile_title: "Profile & Settings",
      profile_photo: "Profile Photo",
      profile_name: "Full Name",
      profile_email: "Email",
      profile_phone: "Phone",
      profile_address: "Address",
      profile_save: "Save Changes",
      profile_change_pass: "Change Password",
      profile_delete: "Delete Account",
      forgot_title: "Forgot Password",
      forgot_email_step: "Enter Email",
      forgot_otp_step: "Verify OTP",
      forgot_pass_step: "New Password",
      forgot_send_otp: "Send OTP",
      forgot_verify: "Verify OTP",
      forgot_reset: "Reset Password",
      forgot_resend: "Resend OTP",
      forgot_success: "Password Reset! ✅",
      expiry_title: "⚠️ Expiring Soon",
      expiry_warning: "expiring soon!",
      expiry_donate: "Donate Now",
      location_share: "Share Live Location",
      location_active: "Live Location Active ✅",
      location_off: "Location Sharing Off",
      location_detecting: "Detecting location...",
      location_denied: "Location access denied"
    },
    hi: {
      nav_features: "विशेषताएं",
      nav_how_it_works: "कैसे काम करता है",
      nav_impact: "प्रभाव",
      nav_login: "लॉगिन",
      nav_signup: "साइन अप",
      nav_dashboard: "डैशबोर्ड",
      nav_donate: "खाना दान करें",
      nav_donations: "मेरे दान",
      nav_track: "ऑर्डर ट्रैक करें",
      nav_stats: "प्रभाव आँकड़े",
      hero_title: "खाना बर्बाद न करें, जरूरतमंदों को खिलाएं",
      hero_subtitle: "अतिरिक्त खाने और NGO के बीच एक सेतु",
      hero_btn_donate: "खाना दान करें",
      hero_btn_find: "खाना खोजें",
      features_title: "FoodBridge क्यों चुनें?",
      feature_1_title: "लोकेशन आधारित मिलान",
      feature_2_title: "सुरक्षित संचालन",
      feature_3_title: "रियल-टाइम ट्रैकिंग",
      feature_4_title: "प्रभाव ट्रैकिंग",
      how_title: "सरल 3-चरण प्रक्रिया",
      step_1_title: "खाने की जानकारी दें",
      step_2_title: "NGO से मिलान करें",
      step_3_title: "पिकअप और डिलीवरी",
      stat_meals: "भोजन दान किए",
      stat_people: "लोगों की मदद",
      stat_donors: "सक्रिय दानकर्ता",
      stat_ngos: "जुड़े NGO",
      footer_tagline: "समुदायों को जोड़कर यह सुनिश्चित करना कि अतिरिक्त खाना जरूरतमंदों तक पहुंचे।",
      login_title: "वापस स्वागत है",
      login_subtitle: "खाना बर्बादी रोकने के अभियान से जुड़ें",
      login_role_donor: "दानकर्ता",
      login_role_ngo: "NGO",
      login_role_admin: "एडमिन",
      login_email: "ईमेल पता",
      login_password: "पासवर्ड",
      login_remember: "मुझे याद रखें",
      login_forgot: "पासवर्ड भूल गए?",
      login_btn: "लॉगिन करें",
      login_no_account: "अकाउंट नहीं है?",
      login_signup: "साइन अप करें",
      login_back_home: "होम पर वापस",
      login_or: "या इससे जारी रखें",
      signup_title: "अकाउंट बनाएं",
      signup_subtitle: "आज FoodBridge से जुड़ें",
      signup_name: "पूरा नाम",
      signup_email: "ईमेल पता",
      signup_phone: "फोन नंबर",
      signup_password: "पासवर्ड",
      signup_confirm: "पासवर्ड confirm करें",
      signup_btn: "अकाउंट बनाएं",
      signup_have_account: "पहले से अकाउंट है?",
      signup_login: "लॉगिन करें",
      donor_welcome: "वापस स्वागत है",
      donor_subtitle: "आज कुछ अच्छा करें",
      donor_new_donation: "नया दान",
      donor_total_donations: "कुल दान",
      donor_meals_provided: "भोजन प्रदान किए",
      donor_people_helped: "लोगों की मदद",
      donor_active: "सक्रिय दान",
      donor_history: "दान इतिहास",
      donor_surplus_title: "क्या आपके पास अतिरिक्त खाना है?",
      donor_surplus_subtitle: "2 मिनट में दान पोस्ट करें",
      donor_impact_title: "इस महीने का आपका प्रभाव 🌟",
      donor_recent_title: "मेरे हाल ही के दान",
      donor_track: "ट्रैक करें",
      donor_status_pending: "लंबित",
      donor_status_accepted: "स्वीकृत",
      donor_status_delivered: "डिलीवर",
      form_title: "नया दान जोड़ें",
      form_food_name: "खाने का नाम",
      form_food_type: "खाने का प्रकार",
      form_quantity: "मात्रा",
      form_expiry: "समाप्ति समय",
      form_address: "पिकअप पता",
      form_notes: "अतिरिक्त नोट्स",
      form_submit: "दान सबमिट करें",
      form_cancel: "रद्द करें",
      ngo_welcome: "स्वागत है",
      ngo_available: "उपलब्ध दान",
      ngo_accepted: "स्वीकृत",
      ngo_schedule: "शेड्यूल",
      ngo_accept_btn: "स्वीकार करें",
      ngo_decline_btn: "अस्वीकार करें",
      ngo_available_subtitle: "दान आज आपके पास उपलब्ध हैं।",
      ngo_sos_alerts: "सक्रिय SOS अलर्ट",
      ngo_sos_recent: "मेरे हाल के SOS",
      ngo_nav_overview: "अवलोकन",
      ngo_nav_available: "उपलब्ध",
      ngo_nav_accepted: "स्वीकृत",
      ngo_nav_schedule: "शेड्यूल",
      ngo_nav_volunteers: "स्वयंसेवक",
      ngo_nav_reports: "रिपोर्ट्स",
      ngo_nav_profile: "प्रोफाइल",
      ngo_stat_available: "मेरे पास उपलब्ध",
      ngo_stat_accepted: "आज स्वीकृत",
      ngo_stat_received: "कुल प्राप्त",
      ngo_stat_volunteers: "सक्रिय स्वयंसेवक",
      admin_title: "एडमिन पैनल",
      admin_users: "कुल उपयोगकर्ता",
      admin_donations: "कुल दान",
      admin_ngos: "सक्रिय NGO",
      admin_complaints: "शिकायतें",
      common_logout: "लॉगआउट",
      common_profile: "प्रोफाइल",
      common_notifications: "सूचनाएं",
      common_settings: "सेटिंग्स",
      common_save: "बदलाव सहेजें",
      common_cancel: "रद्द करें",
      common_delete: "हटाएं",
      common_search: "खोजें...",
      common_loading: "लोड हो रहा है...",
      common_no_data: "कोई डेटा नहीं",
      common_back: "वापस",
      sos_title: "फूड SOS 🆘",
      sos_subtitle: "बहुत खाना है? तुरंत NGO चाहिए?",
      sos_btn: "SOS अलर्ट भेजें",
      sos_sending: "अलर्ट भेजा जा रहा है...",
      sos_sent: "SOS अलर्ट भेजा गया! ✅",
      sos_active: "सक्रिय SOS अलर्ट",
      sos_cancel: "SOS रद्द करें",
      sos_history: "पिछले SOS अलर्ट",
      notif_title: "सूचनाएं",
      notif_mark_all: "सभी पढ़ा हुआ चिह्नित करें",
      notif_empty: "अभी कोई सूचना नहीं",
      profile_title: "प्रोफाइल और सेटिंग्स",
      profile_photo: "प्रोफाइल फोटो",
      profile_name: "पूरा नाम",
      profile_email: "ईमेल",
      profile_phone: "फोन",
      profile_address: "पता",
      profile_save: "बदलाव सहेजें",
      profile_change_pass: "पासवर्ड बदलें",
      profile_delete: "अकाउंट हटाएं",
      forgot_title: "पासवर्ड भूल गए",
      forgot_email_step: "ईमेल दर्ज करें",
      forgot_otp_step: "OTP verify करें",
      forgot_pass_step: "नया पासवर्ड",
      forgot_send_otp: "OTP भेजें",
      forgot_verify: "OTP verify करें",
      forgot_reset: "पासवर्ड रीसेट करें",
      forgot_resend: "OTP दोबारा भेजें",
      forgot_success: "पासवर्ड रीसेट हो गया! ✅",
      expiry_title: "⚠️ जल्द समाप्त होगा",
      expiry_warning: "जल्द समाप्त होगा!",
      expiry_donate: "अभी दान करें",
      location_share: "लाइव लोकेशन शेयर करें",
      location_active: "लाइव लोकेशन सक्रिय ✅",
      location_off: "लोकेशन शेयरिंग बंद",
      location_detecting: "लोकेशन ढूंढ रहे हैं...",
      location_denied: "लोकेशन एक्सेस नहीं मिली"
    }
  },

  get: () => {
    return localStorage.getItem('fb_lang') || 'en';
  },

  set: (lang) => {
    localStorage.setItem('fb_lang', lang);
    localStorage.setItem('fb_language', lang === 'hi' ? 'hindi' : 'english');
    document.documentElement.setAttribute('lang', lang);
    FBLang.apply();
  },

  apply: () => {
    const lang = FBLang.get();
    const t = FBLang.translations[lang] || FBLang.translations['en'];

    // Update data-t attributes
    document.querySelectorAll('[data-t]').forEach(el => {
      const key = el.dataset.t;
      if (t[key]) {
        el.textContent = t[key];
      }
    });

    // Update data-t-placeholder
    document.querySelectorAll('[data-t-placeholder]').forEach(el => {
      const key = el.dataset.tPlaceholder;
      if (t[key]) {
        el.setAttribute('placeholder', t[key]);
      }
    });

    // Update document styles
    document.body.classList.remove('hindi', 'english');
    document.body.classList.add(lang === 'hi' ? 'hindi' : 'english');

    // Update standard switchers
    document.querySelectorAll('.lang-btn').forEach(btn => {
      btn.classList.toggle('active', btn.dataset.lang === lang);
    });
  },

  init: () => {
    document.addEventListener('DOMContentLoaded', () => {
      FBLang.apply();
    });
  }
};

FBLang.init();

// --- Compatibility Interfaces (React fallback) ---
window.getLang = () => {
  const lang = FBLang.get();
  return lang === 'hi' ? 'hindi' : 'english';
};

window.setLang = (lang) => {
  const shortLang = lang === 'hindi' || lang === 'hi' ? 'hi' : 'en';
  FBLang.set(shortLang);
};

window.t = (key) => {
  const lang = FBLang.get();
  const t = FBLang.translations[lang] || FBLang.translations['en'];
  return t[key] || FBLang.translations['en'][key] || key;
};
